<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Bogus" />
        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="MartinCostello.Logging.XUnit.v3" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Respawn" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\EntityFrameworkCore.Encrypted\EntityFrameworkCore.Encrypted.csproj" />
    </ItemGroup>

</Project>
