using System.Globalization;
using Amazon.KeyManagementService;
using Amazon.KeyManagementService.Model;
using EntityFrameworkCore.Encrypted.Keys;

namespace EntityFrameworkCore.Encrypted.AwsKms;

/// <summary>
/// Root keys are generated by KMS (<c>GenerateDataKey</c>, AES-256) and unwrapped with <c>Decrypt</c>:
/// one KMS call per root key. The root key id is part of the encryption context, so wrapped keys can't be swapped.
/// </summary>
internal sealed class AwsKmsKeyWrapper(IAmazonKeyManagementService kms, AwsKmsOptions options) : IKeyWrapper
{
    internal const string ReservedContextPrefix = "efenc:";

    public async Task<GeneratedRootKey> GenerateAsync(int rootKeyId, CancellationToken cancellationToken)
    {
        var response = await kms.GenerateDataKeyAsync(new GenerateDataKeyRequest
        {
            KeyId = options.KeyId,
            KeySpec = DataKeySpec.AES_256,
            EncryptionContext = CreateEncryptionContext(rootKeyId)
        }, cancellationToken);

        await using var plaintext = response.Plaintext;
        await using var ciphertext = response.CiphertextBlob;

        return new GeneratedRootKey(plaintext.ToArray(), response.KeyId, ciphertext.ToArray());
    }

    public async Task<byte[]> UnwrapAsync(WrappedRootKey rootKey, CancellationToken cancellationToken)
    {
        var response = await kms.DecryptAsync(new DecryptRequest
        {
            KeyId = rootKey.WrappingKeyId,
            CiphertextBlob = new MemoryStream(rootKey.WrappedKey),
            EncryptionContext = CreateEncryptionContext(rootKey.Id)
        }, cancellationToken);

        await using var plaintext = response.Plaintext;
        return plaintext.ToArray();
    }

    private Dictionary<string, string> CreateEncryptionContext(int rootKeyId)
        => new(options.EncryptionContext)
        {
            [ReservedContextPrefix + "purpose"] = "root-key",
            [ReservedContextPrefix + "root-key-id"] = rootKeyId.ToString(CultureInfo.InvariantCulture)
        };
}
