using System.Globalization;
using Amazon.KeyManagementService;
using Amazon.KeyManagementService.Model;
using EntityFrameworkCore.Encrypted.Keys;

namespace EntityFrameworkCore.Encrypted.AwsKms;

/// <summary>
/// Root keys are generated by KMS (<c>GenerateDataKey</c>, AES-256) and unwrapped with <c>Decrypt</c>:
/// one KMS call per root key, and moved to another KMS key with <c>ReEncrypt</c>.
/// The root key id is part of the encryption context, so wrapped keys can't be swapped.
/// </summary>
internal sealed class AwsKmsKeyWrapper(IAmazonKeyManagementService kms, AwsKmsOptions options) : IKeyWrapper
{
    internal const string ReservedContextPrefix = "efenc:";

    public async Task<GeneratedRootKey> GenerateAsync(int rootKeyId, CancellationToken cancellationToken)
    {
        var response = await kms.GenerateDataKeyAsync(new GenerateDataKeyRequest
        {
            KeyId = options.KeyId,
            KeySpec = DataKeySpec.AES_256,
            EncryptionContext = CreateEncryptionContext(rootKeyId)
        }, cancellationToken);

        await using var plaintext = response.Plaintext;
        await using var ciphertext = response.CiphertextBlob;

        return new GeneratedRootKey(plaintext.ToArray(), response.KeyId, ciphertext.ToArray());
    }

    public async Task<byte[]> UnwrapAsync(WrappedRootKey rootKey, CancellationToken cancellationToken)
    {
        var response = await kms.DecryptAsync(new DecryptRequest
        {
            KeyId = rootKey.WrappingKeyId,
            CiphertextBlob = new MemoryStream(rootKey.WrappedKey),
            EncryptionContext = CreateEncryptionContext(rootKey.Id)
        }, cancellationToken);

        await using var plaintext = response.Plaintext;
        return plaintext.ToArray();
    }

    /// <summary>
    /// KMS <c>ReEncrypt</c>: the root key is decrypted and encrypted with the configured KMS key inside KMS.
    /// Requires <c>kms:ReEncryptFrom</c> on the old key and <c>kms:ReEncryptTo</c> on the new one.
    /// </summary>
    public async Task<WrappedRootKey> RewrapAsync(WrappedRootKey rootKey, CancellationToken cancellationToken)
    {
        var encryptionContext = CreateEncryptionContext(rootKey.Id);

        var response = await kms.ReEncryptAsync(new ReEncryptRequest
        {
            SourceKeyId = rootKey.WrappingKeyId,
            SourceEncryptionContext = encryptionContext,
            DestinationKeyId = options.KeyId,
            DestinationEncryptionContext = encryptionContext,
            CiphertextBlob = new MemoryStream(rootKey.WrappedKey)
        }, cancellationToken);

        await using var ciphertext = response.CiphertextBlob;
        return rootKey with { WrappingKeyId = response.KeyId, WrappedKey = ciphertext.ToArray() };
    }

    private Dictionary<string, string> CreateEncryptionContext(int rootKeyId)
        => new(options.EncryptionContext)
        {
            // root key id 0 is the blind index key of the context
            [ReservedContextPrefix + "purpose"] = rootKeyId == 0 ? "index-key" : "root-key",
            [ReservedContextPrefix + "root-key-id"] = rootKeyId.ToString(CultureInfo.InvariantCulture)
        };
}
