<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>EntityFrameworkCore.Encrypted.Postgres.AwsWrapping</Title>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\EntityFrameworkCore.Encrypted\EntityFrameworkCore.Encrypted.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" />
        <PackageReference Include="AWSSDK.KeyManagementService" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="EntityFrameworkCore.Encrypted.Tests.Postgres.AwsWrapping" />
    </ItemGroup>

</Project>
