// <auto-generated />
using System;
using EntityFrameworkCore.Encrypted.Tests.Postgres.Common.TestContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntityFrameworkCore.Encrypted.Tests.Postgres.Common.TestContext.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameworkCore.Encrypted.Common.Storage.EncryptionKeyEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("WrappedKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("WrappingKeyId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.ToTable("__EncryptionKeys");
                });

            modelBuilder.Entity("EntityFrameworkCore.Encrypted.Tests.Postgres.Common.TestContext.Password", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedAttribute")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("EncryptedBinary")
                        .HasColumnType("bytea");

                    b.Property<string>("EncryptedFluent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Microsoft.EntityFrameworkCore.Encrypted.IsEncrypted", true);

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Passwords");
                });
#pragma warning restore 612, 618
        }
    }
}
