using Amazon.KeyManagementService;
using EntityFrameworkCore.Encrypted;
using EntityFrameworkCore.Samples.Encryption.AwsKms.Common;
using EntityFrameworkCore.Samples.Encryption.AwsKms.Database;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddHostedService<MigrationHostedService>();

// localstack; in AWS the client is registered from the AWS configuration automatically
builder.Services.AddSingleton<IAmazonKeyManagementService>(new AmazonKeyManagementServiceClient(
    new AmazonKeyManagementServiceConfig
    {
        ServiceURL = "http://localhost:4566"
    }));

// root key is generated by KMS on first start and stored wrapped in the __EncryptionKeys table
builder.Services
    .AddEncryption(x => x.UseAwsKms(builder.Configuration.GetValue<string>("Database:KmsKeyId")!))
    .AddDbContext<EncryptedDbContext>(x => x
        .UseNpgsql(builder.Configuration.GetValue<string>("Database:ConnectionString"))
        .UseEncryption());

var app = builder.Build();

app.UseSwagger();
app.UseSwaggerUI();
app.UseHttpsRedirection();

app.MapGet("/passwords", (EncryptedDbContext context, CancellationToken ct)
        => context.EncryptedPasswords.ToListAsync(ct));

app.MapPost("/passwords", async (string password, EncryptedDbContext context, CancellationToken ct) =>
    {
        context.Add(new PasswordWithEncryption
        {
            EncryptedFluent = password,
            EncryptedAttribute = password,
            Original = password
        });

        await context.SaveChangesAsync(ct);
    });

app.MapPost("/keys/rotate", (IServiceProvider services, CancellationToken ct)
    => services.RotateRootKeyAsync<EncryptedDbContext>(ct));

app.MapGet("/keys/usage", (IServiceProvider services, CancellationToken ct)
    => services.GetKeyUsageAsync<EncryptedDbContext>(ct));

app.MapPost("/keys/re-encrypt", (IServiceProvider services, CancellationToken ct)
    => services.ReEncryptAsync<EncryptedDbContext>(cancellationToken: ct));

app.MapPost("/keys/rewrap", (IServiceProvider services, CancellationToken ct)
    => services.RewrapRootKeysAsync<EncryptedDbContext>(ct));

app.Run();
