using Amazon.KeyManagementService;
using Amazon.Runtime;
using EntityFrameworkCore.Encrypted;
using EntityFrameworkCore.Samples.Encryption.AwsKms.Common;
using EntityFrameworkCore.Samples.Encryption.AwsKms.Database;
using Microsoft.EntityFrameworkCore;
using OpenTelemetry.Metrics;
using OpenTelemetry.Trace;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddOpenApi();

// registered before AddEncryption: the database is migrated before the keys are loaded
builder.Services.AddHostedService<MigrationHostedService>();

// LocalStack (docker compose); without this registration the client comes from the AWS configuration
builder.Services.AddSingleton<IAmazonKeyManagementService>(new AmazonKeyManagementServiceClient(
    new BasicAWSCredentials("test", "test"),
    new AmazonKeyManagementServiceConfig { ServiceURL = "http://localhost:4566", AuthenticationRegion = "us-east-1" }));

// root key is generated by KMS on first start and stored wrapped in the __EncryptionKeys table;
// every instance checks for a root key rotated by another instance every 5 minutes
builder.Services
    .AddEncryption(x => x
        .UseAwsKms(builder.Configuration["Encryption:KmsKeyId"]!)
        .RefreshRootKeysEvery(TimeSpan.FromMinutes(5)))
    .AddDbContext<EncryptedDbContext>(x => x
        .UseNpgsql(builder.Configuration["Database:ConnectionString"])
        .UseEncryption());

builder.Services.AddHealthChecks().AddEncryptionKeys();

// KMS calls, key loads, rotation and re-encryption as traces; value counts, failures and KMS latency as metrics
builder.Services.AddOpenTelemetry()
    .WithTracing(x => x.AddAspNetCoreInstrumentation().AddSource(EncryptionInstrumentation.Name).AddConsoleExporter())
    .WithMetrics(x => x.AddMeter(EncryptionInstrumentation.Name).AddConsoleExporter());

var app = builder.Build();

// create the OpenTelemetry providers before the host starts, so the root key loaded on startup is traced too
app.Services.GetRequiredService<TracerProvider>();
app.Services.GetRequiredService<MeterProvider>();

app.MapOpenApi();
app.MapHealthChecks("/health");

app.MapGet("/passwords", (EncryptedDbContext context, CancellationToken ct)
        => context.EncryptedPasswords.ToListAsync(ct));

app.MapPost("/passwords", async (string password, EncryptedDbContext context, CancellationToken ct) =>
    {
        context.Add(new PasswordWithEncryption
        {
            EncryptedFluent = password,
            EncryptedAttribute = password,
            Original = password
        });

        await context.SaveChangesAsync(ct);
    });

// key management: an admin API or a one-off job in a real application

// new root key (1 KMS GenerateDataKey); new values use it, older values stay readable
app.MapPost("/keys/rotate", (IServiceProvider services, CancellationToken ct)
    => services.RotateRootKeyAsync<EncryptedDbContext>(ct));

// values per table, column and key: when a root key is no longer listed, no value uses it
app.MapGet("/keys/usage", (IServiceProvider services, CancellationToken ct)
    => services.GetKeyUsageAsync<EncryptedDbContext>(ct));

// re-encrypt values that don't use the active key, in batches; safe while the application is running
app.MapPost("/keys/re-encrypt", (IServiceProvider services, CancellationToken ct)
    => services.ReEncryptAsync<EncryptedDbContext>(batchSize: 500, cancellationToken: ct));

// after changing Encryption:KmsKeyId: re-encrypt root keys with the new KMS key (KMS ReEncrypt), values untouched
app.MapPost("/keys/rewrap", (IServiceProvider services, CancellationToken ct)
    => services.RewrapRootKeysAsync<EncryptedDbContext>(ct));

app.Run();
