// <auto-generated />
using System;
using EntityFrameworkCore.Encryption.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntityFrameworkCore.Encryption.Postgres.Migrations
{
    [DbContext(typeof(MetadataContext))]
    partial class MetadataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("encrypt")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameworkCore.Encryption.Metadata.KeyMetadata", b =>
                {
                    b.Property<string>("ContextId")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RotationToken")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ContextId");

                    b.ToTable("Metadata", "encrypt");
                });
#pragma warning restore 612, 618
        }
    }
}
