<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>EntityFrameworkCore.Encrypted</Title>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="EntityFrameworkCore.Encrypted.Postgres.AwsWrapping" />
        <InternalsVisibleTo Include="EntityFrameworkCore.Encrypted.Tests.Postgres" />
        <InternalsVisibleTo Include="EntityFrameworkCore.Encrypted.Tests.Postgres.AwsWrapping" />
        <InternalsVisibleTo Include="EntityFrameworkCore.Encrypted.Tests.Postgres.Shared" />
    </ItemGroup>

</Project>
