title: EF Core Encrypted
description: Application-side encryption of EF Core entity properties
url: https://starushykart.github.io
baseurl: /ef-core-encryption

remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-remote-theme

search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: Back to top

aux_links:
  GitHub: https://github.com/starushykart/ef-core-encryption
  NuGet: https://www.nuget.org/packages/EntityFrameworkCore.Encrypted

gh_edit_link: true
gh_edit_link_text: Edit this page on GitHub
gh_edit_repository: https://github.com/starushykart/ef-core-encryption
gh_edit_branch: main
gh_edit_source: docs
gh_edit_view_mode: edit

footer_content: Licensed under <a href="https://github.com/starushykart/ef-core-encryption/blob/main/LICENSE">MIT</a>.

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: purple
  warning:
    title: Warning
    color: red
