name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    
    - name: Set Version Variable
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1

    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test -c Release --no-build

    - name: Pack EntityFrameworkCore.Encrypted
      run: dotnet pack src/EntityFrameworkCore.Encrypted -c Release --no-build --output . /p:PackageVersion=$VERSION

    - name: Pack EntityFrameworkCore.Encrypted.Postgres.AwsWrapping
      run: dotnet pack src/EntityFrameworkCore.Encrypted.Postgres.AwsWrapping -c Release --no-build --output . /p:PackageVersion=$VERSION

    - name: Push to NuGet packages
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
